version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-emedical}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-emedical}
      POSTGRES_DB: ${DB_NAME:-emedical}
    ports:
      - '${DB_PORT:-5434}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
